# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.1
language: objective-c
cache: cocoapods
podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# install:
# - |
#   bundle install
#   pod repo update --silent
#   pod install
before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail
- xcodebuild clean test -workspace Example/CPMenuView.xcworkspace -scheme CPMenuView_Example -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" -enableCodeCoverage YES | xcpretty
- pod lib lint --allow-warnings

  